#!/bin/bash
i=1
if [ ! -n "${1}" ];then
echo "Please use: $0 <logfile> [tag]"
exit -1
fi
if [ -n "${2}" ];then
    tag="${2}"
else
    tag="router6000"
fi
path=`pwd`
target="${path}/${1}"
while [ $i -lt 10 ];
do
grep -E "ADM-DUT$i|ADM-DEVICE$i" $target
if [ "$?" != "0" ];then
    i=`expr $i + 1`
    continue;
fi
dut="${path}/DEVICE${i}_CMD"
cat $target > $dut
sed -i "/localhost(\|sp-sc1(\|ericsson(\|sf-rp-s9m(\|router6000(\|Ericsson(\|localhost#\|sp-sc1#\|ericsson#\|sf-rp-s9m#\|router6000#\|Ericsson#/!d" "$dut"
sed -i "/^ADM-DUT$i\|^ADM-DEVICE$i/!d" "$dut"
sed -i "s/^ADM-DUT.*#\|^ADM-DEVICE.*#//g" "$dut"
i=`expr $i + 1`
done
