#!/bin/bash
i=1
if [ ! -n "${1}" ];then
echo "Please use: $0 <logfile> [tag]"
exit -1
fi
if [ -n "${2}" ];then
    tag="${2}"
else
    tag="router6000"
fi
path=`pwd`
target="${path}/${1}"
while [ $i -lt 10 ];
do
grep "ADM-DUT$i" $target
if [ "$?" != "0" ];then
    i=`expr $i + 1`
    continue;
fi
dut="${path}/DUT${i}_CMD"
cat $target > $dut
sed -i "/\($tag#\|$tag(\)/!d" "$dut"
sed -i "/^ADM-DUT$i/!d" "$dut"
sed -i "s/^ADM-DUT.*#//g" "$dut"
#sed -i "1iconfig" "$dut"
#sed -i "/^end/aconfig" "$dut"
#sed -i '$s/config//g' "$dut"
i=`expr $i + 1`
done
